# Jason Turner #80: https://www.youtube.com/watch?v=R8OrWVVf5CM

# https://www.appveyor.com/docs/windows-images-software/#visual-studio-2019
images: 
  - Visual Studio 2019

environment:
  matrix:
  - ARCH: x64

build_script:
- cmake -G "Visual Studio 14 2015" .
- cmake --build .

test_script:
- ctest -C Debug -VV